services:
  - type: web
    name: profile-rewriter
    env: python
    region: oregon # Adjust to your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: DEBUG # Or adjust based on preference
